name: IBCtestenv
channels:
  - conda-forge
  - defaults
dependencies:
  - aiohttp=3.9.5
  - aiosignal=1.3.1
  - aom=3.9.0
  - async-timeout=4.0.3
  - attrs=23.2.0
  - blosc=1.21.5
  - bzip2=1.0.8
  - ca-certificates=2024.6.2
  - cairo=1.18.0
  - cgal-cpp=5.6.1
  - colorama=0.4.6
  - console_shortcut=0.1.1
  - dav1d=1.2.1
  - double-conversion=3.3.0
  - eigen=3.4.0
  - expat=2.5.0
  - ffmpeg=6.1.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freeimage=3.18.0
  - freetype=2.12.1
  - frozenlist=1.4.1
  - gl2ps=1.4.2
  - glew=2.1.0
  - glib=2.80.2
  - glib-tools=2.80.2
  - graphite2=1.3.13
  - gst-plugins-base=1.24.4
  - gstreamer=1.24.4
  - harfbuzz=8.5.0
  - hdf4=4.2.15
  - hdf5=1.14.3
  - icu=73.2
  - idna=3.7
  - ifcopenshell=v0.7.0.231127
  - imath=3.1.11
  - intel-openmp=2024.1.0
  - jsoncpp=1.9.5
  - jxrlib=1.1
  - krb5=1.21.2
  - lcms2=2.16
  - lerc=4.0.0
  - libaec=1.1.3
  - libblas=3.9.0
  - libboost=1.82.0
  - libboost-devel=1.82.0
  - libboost-headers=1.82.0
  - libcblas=3.9.0
  - libclang13=18.1.6
  - libcurl=8.8.0
  - libdeflate=1.20
  - libexpat=2.5.0
  - libffi=3.4.2
  - libglib=2.80.2
  - libhwloc=2.10.0
  - libiconv=1.17
  - libintl=0.22.5
  - libintl-devel=0.22.5
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - libnetcdf=4.9.2
  - libogg=1.3.4
  - libopus=1.3.1
  - libpng=1.6.43
  - libraw=0.21.1
  - libsqlite=3.45.3
  - libssh2=1.11.0
  - libtheora=1.1.1
  - libtiff=4.6.0
  - libvorbis=1.3.7
  - libwebp-base=1.4.0
  - libxml2=2.12.7
  - libzip=1.10.1
  - libzlib=1.2.13
  - loguru=0.7.2
  - lz4-c=1.9.4
  - mkl=2024.1.0
  - mpfr=4.2.1
  - mpir=3.0.0
  - msgpack-python=1.0.8
  - multidict=6.0.5
  - nlohmann_json=3.11.3
  - numpy=1.26.4
  - occt=7.7.2
  - openexr=3.2.2
  - openh264=2.4.1
  - openjpeg=2.5.2
  - openssl=3.3.0
  - pcre2=10.43
  - pixman=0.43.4
  - powershell_shortcut=0.0.1
  - proj=9.3.1
  - pthreads-win32=2.9.1
  - pugixml=1.14
  - python=3.9.19
  - python_abi=3.9
  - qt-main=5.15.8
  - rapidjson=1.1.0.post20240409
  - snappy=1.1.10
  - sqlite=3.45.3
  - svt-av1=2.1.0
  - tbb=2021.12.0
  - tbb-devel=2021.12.0
  - typing-extensions=4.12.1
  - typing_extensions=4.12.1
  - ucrt=10.0.22621.0
  - utfcpp=4.0.5
  - vc=14.2
  - vc14_runtime=14.38.33135
  - vs2015_runtime=14.38.33135
  - vtk=9.2.6
  - vtk-base=9.2.6
  - wheel=0.43.0
  - win32_setctime=1.1.0
  - wslink=2.0.4
  - x264=1!164.3095
  - x265=3.5
  - xz=5.2.6
  - yarl=1.9.4
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - annotated-types==0.7.0
      - anyio==4.4.0
      - appdirs==1.4.4
      - argparse==1.4.0
      - backoff==2.2.1
      - blinker==1.8.2
      - certifi==2024.6.2
      - cffi==1.16.0
      - charset-normalizer==3.3.2
      - click==8.1.7
      - cors==1.0.1
      - deprecated==1.2.14
      - exceptiongroup==1.2.1
      - filelock==3.14.0
      - flask==3.0.3
      - flask-cors==4.0.1
      - future==1.0.0
      - fuzzywuzzy==0.18.0
      - gevent==24.2.1
      - ghhops-server==1.5.5
      - gql==3.5.0
      - graphql-core==3.2.3
      - greenlet==3.0.3
      - h11==0.14.0
      - httpcore==1.0.5
      - httpx==0.25.2
      - importlib-metadata==7.1.0
      - itsdangerous==2.2.0
      - jinja2==3.1.4
      - lark==1.1.9
      - levenshtein==0.25.1
      - markupsafe==2.1.5
      - packaging==24.0
      - pandas==2.2.2
      - pip==24.2
      - plotly==5.22.0
      - pycparser==2.22
      - pydantic==2.7.2
      - pydantic-core==2.18.3
      - pysocks==1.7.1
      - python-dateutil==2.9.0.post0
      - python-levenshtein==0.25.1
      - pytz==2024.1
      - rapidfuzz==3.9.4
      - requests==2.32.3
      - requests-file==2.1.0
      - requests-toolbelt==1.0.0
      - rhino3dm==8.9.0
      - scipy==1.13.1
      - setuptools==70.2.0
      - six==1.16.0
      - sniffio==1.3.1
      - specklepy==2.19.2
      - stringcase==1.2.0
      - tenacity==8.3.0
      - tldextract==5.1.2
      - topologic-core==8.0.0
      - topologicpy==0.7.12
      - tqdm==4.66.4
      - tzdata==2024.1
      - ujson==5.10.0
      - urllib3==2.2.1
      - websockets==11.0.3
      - werkzeug==3.0.3
      - wrapt==1.16.0
      - zipp==3.19.2
      - zope-event==5.0
      - zope-interface==6.4.post2
prefix: C:\Users\panz\.conda\envs\ifctestenv
